# Generated by Django 3.1 on 2021-05-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('Eng', 'English'), ('HIN', 'Hindi'), ('TAM', 'Tamil'), ('TEL', 'Telugu')], max_length=3)),
                ('certificate', models.CharField(choices=[('U', 'U'), ('UA', 'U/A'), ('A', 'A'), ('R', 'R')], max_length=2)),
                ('popularity_index', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('BLR', 'Bangalore'), ('DEL', 'Delhi'), ('MUM', 'Mumbai'), ('PUN', 'Pune'), ('CHN', 'Chennai')], max_length=3)),
                ('address', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=3, null=True)),
                ('seat_type', models.CharField(choices=[('', 'Select'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=8)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.show')),
            ],
            options={
                'unique_together': {('no', 'show')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('cd', 'Credit Card'), ('db', 'Debit Card')], default='Credit Card', max_length=2)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.seat')),
            ],
            options={
                'unique_together': {('seat', 'booking')},
            },
        ),
    ]
